server:
  port: 2343

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/employeedev
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  
---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/employeeqa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    


---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/employeeprod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
